name: Deploy React.js Menu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy Files to VPS
      run: |
        rsync -avz --delete --exclude=".git" -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/root/frontend

    - name: Install Dependencies and Build App
      run: |
        ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd /root/frontend  # Use the correct path used in rsync
          npm install
          if [ -f .env.production ]; then
            cp .env.production .env
          fi
          NODE_ENV=production npm run build
          if [ -d build ]; then
            sudo cp -rf build/* /usr/share/nginx/html/menu
          else
            echo "Build directory not found!"
            exit 1
          fi
        EOF

